### PR TITLE
fix(select-item): export `class` and `style` props

### LINKED ISSUE #1839: `SelectItem` properties `style`/`class` missing from types.
The values for `style`/`class` are pulled from `$$restProps` but the types only contain the defined props, leading to errors when using TypeScript.

https://github.com/carbon-design-system/carbon-components-svelte/blob/fee236194bbfc7aa9225fe694aa0c7fc098dd6dc/src/Select/SelectItem.svelte#L35-L43

Properties should probably either be explicit or all `$$restProps` should be spread along with a `/** @restProps {option} */` annotation.

### PR DESCRIPTION
**Pull request by metonym**
Fixes #1839 

`SelectItem` is missing type definitions for the `class` and `style` props. Even though this defines props on the component, this is not a breaking change as the behavior has always been supported.

### CODE REVIEW

File: src/Select/SelectItem.svelte [hunk 1]
```diff
@@ -14,6 +14,14 @@
   /** Set to `true` to disable the option */
   export let disabled = false;
 
+  let className = "";
+
+  /** Specify the class of the `option` element */
+  export { className as class };
+
+  /** Specify the style of the `option` element */
+  export let style = "";
```
Comment (brunnerh) [inline src/Select/SelectItem.svelte:23]: Would suggest `undefined` so the attribute is not added unnecessarily.
(Could also be done for `class`, but there already is a Carbon class on the element.

```suggestion
  /**
   * Specify the style of the `option` element
   * @type {string}
   */
  export let style = undefined;
```

Comment (metonym) [reply src/Select/SelectItem.svelte]: Good catch – amended.

**Review by brunnerh — APPROVED** [review]

**Review by theetrain — APPROVED** [review]
Neat, I can ship this Monday evening, but if you get to it first then go ahead.

**Comment by metonym** [comment]
Released in [v0.81.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.81.3)
